[project]
name = "24-718-computational-fluid-dynamics-project"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jax>=0.6.2",
    "matplotlib>=3.10.7",
    "pint>=0.24.4",
    "tqdm>=4.67.1",
]
